server:
  servlet:
    path: /*
    context-path: /friends-management
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    username: raj
    password: test1234
logging:
  config: classpath:logback.xml